version: '3.4'

services:
  reacthomeworktemplate:
    image: reacthomeworktemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: moviesApp_c
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
